{
  try {
    return getConfirmationMessage(object);
  }
 catch (  IOException ioEx) {
    throw new RuntimeException(ioEx);
  }
catch (  Exception e) {
    throw new RuntimeException("A data object that does not have " + "a 'name' property has been used, this is unexpected",e);
  }
}
