{
  try {
    callInternal();
  }
 catch (  Exception e) {
    exception=e;
    throw e;
  }
  return loops;
}
